# Apache 2.0 License
#
# Copyright (c) 2018 Sebastian Katzer, appPlant GmbH
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

language: generic
sudo: false

os:
- linux

matrix:
  include:
  - env: MRUBY_VERSION=1.4.1
    services: [docker]
    sudo: false
  - env: MRUBY_VERSION=head
    services: [docker]
    sudo: false
    before_install:
    - if [ "$TRAVIS_TAG" ]; then travis_terminate 0; fi;
  allow_failures:
  - env: MRUBY_VERSION=head

script:
- if [[ $TRAVIS_COMMIT_MESSAGE == *\\[ci-compile\\]* ]]; then rake compile; else echo 'skip compile'; fi;
- if [[ $TRAVIS_TAG ]]; then echo 'skip test'; else rake test:bintest; fi;

before_deploy:
- rake release
- mruby/build/x86_64-pc-linux-gnu-glibc-2.12/bin/plip -v
- mruby/build/x86_64-pc-linux-gnu/bin/plip -v
- sudo chmod -R 1777 releases
- sudo chmod -R 1777 mruby/build/host/mrbgems
- export BUILD_VERSION=`rake local:version`
- echo $BUILD_VERSION
- ls -la releases
- ls -la releases/v$BUILD_VERSION

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-apple-darwin15.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-alpine-linux-musl.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-pc-linux-gnu.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-pc-linux-gnu-glibc-2.12.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-w64-mingw32.tgz"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition:
    - "$MRUBY_VERSION == 1.4.1"
    - "$TRAVIS_OS_NAME == linux"
