language: go
sudo: false

os:
- linux

services:
- docker

before_script:
- chmod u+x scripts/*

script:
- scripts/bintest

before_deploy:
- scripts/release
- gem install --no-ri --no-rdoc os
- export BUILD_VERSION=`rake version`
- sudo chmod -R 1777 releases
- ls -la releases
- ls -la releases/v$BUILD_VERSION

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-i386-apple-darwin15.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-i686-pc-linux-gnu.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-i686-pc-linux-gnu-glibc-2.12.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-i686-w64-mingw32.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-apple-darwin15.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-alpine-linux-musl.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-pc-linux-gnu.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-pc-linux-gnu-glibc-2.12.tgz"
  - "releases/v$BUILD_VERSION/plip-$BUILD_VERSION-x86_64-w64-mingw32.tgz"
  skip_cleanup: true
  on:
    tags: true
    condition:
    - "$TRAVIS_OS_NAME == linux"
